In [2]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [8]:
arr.ndim

1

In [9]:
arr1.ndim

2

In [10]:
np.matrix(l) #matrix have two dimension

matrix([[1, 2, 3, 4, 5]])

In [11]:
mat = np.matrix(l) #matrix have two dimension

In [12]:
np.asanyarray(mat) # matrix is type of array

matrix([[1, 2, 3, 4, 5]])

In [13]:
 a = arr

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
arr[0] = 100

In [16]:
arr

array([100,   2,   3,   4,   5])

In [17]:
a# solo copy operation

array([100,   2,   3,   4,   5])

In [18]:
b = np.copy(arr) # deep copy

In [19]:
b

array([100,   2,   3,   4,   5])

In [20]:
b[0]=234

In [21]:
b

array([234,   2,   3,   4,   5])

In [22]:
arr

array([100,   2,   3,   4,   5])

In [23]:
np.fromfunction(lambda i,j : i==j ,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
arr.shape

(5,)

In [25]:
arr1.shape

(2, 3)

In [26]:
arr.size

5

In [27]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
for i in range(5):
   print(i)

0
1
2
3
4


In [29]:
(i*i for i in  range(5))

<generator object <genexpr> at 0x000002182E88CC70>

In [30]:
list(i*i for i in  range(5))

[0, 1, 4, 9, 16]

In [31]:
iterable = (i*i for i in  range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('23 45 56',sep = ' ')

array([23., 45., 56.])

In [34]:
np.fromstring('23,45,56',sep = ',')

array([23., 45., 56.])

In [35]:
np.fromstring('jyoti,Raghav,Ryon',sep = ',') #only number cn do it

C:\Users\jtrmb\AppData\Local\Temp\ipykernel_2932\1639164402.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('jyoti,Raghav,Ryon',sep = ',') #only number cn do it


array([], dtype=float64)

In [36]:
l=[1,2,3,"Ayaj"]
arr=np.array(l)
arr.dtype

dtype('<U11')

In [37]:
l=[1,2,3,]
arr=np.array(l)
arr.dtype

dtype('int32')

In [38]:
list(range(5))

[0, 1, 2, 3, 4]

In [39]:
range(5)

range(0, 5)

In [40]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
list(range(1.0,2.0))

TypeError: 'float' object cannot be interpreted as an integer

In [42]:
list(np.arange(0.1,10.2,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001]

In [44]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [45]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [47]:
np.logspace(1,5,base=2)

array([ 2.        ,  2.11642982,  2.2396376 ,  2.37001791,  2.50798829,
        2.65399061,  2.80849244,  2.97198858,  3.14500263,  3.32808868,
        3.52183307,  3.72685628,  3.94381489,  4.17340372,  4.41635805,
        4.67345595,  4.94552078,  5.23342383,  5.53808714,  5.8604864 ,
        6.2016541 ,  6.56268285,  6.94472885,  7.34901563,  7.77683793,
        8.22956587,  8.70864932,  9.21562258,  9.75210923, 10.31982742,
       10.92059526, 11.55633675, 12.22908788, 12.94100316, 13.69436252,
       14.49157863, 15.3352046 , 16.22794219, 17.17265042, 18.17235475,
       19.23025679, 20.3497445 , 21.53440308, 22.78802646, 24.11462942,
       25.51846045, 27.00401538, 28.57605177, 30.23960411, 32.        ])

In [48]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [49]:
np.logspace(1,5,10,base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [50]:
arr1=np.zeros(5)
arr1.shape

(5,)

In [51]:
arr2=np.zeros((3,4))
arr2.shape

(3, 4)

In [52]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr1

array([0., 0., 0., 0., 0.])

In [54]:
arr3=np.zeros((3,3,4))
arr3.shape

(3, 3, 4)

In [56]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [57]:
arr3.ndim

3

In [58]:
arr.ndim

1

In [60]:
arr4=np.zeros((1,3,3,4))
arr4.shape

(1, 3, 3, 4)

In [62]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [63]:
arr4.ndim

4

In [64]:
arr1.ndim# tells dimension

1

In [65]:
arr.size

3

In [ ]:
arr1.size

In [66]:
arr1.shape

(5,)

In [ ]:
arr.dtype

In [67]:
arr1.dtype

dtype('float64')

In [ ]:
arr1

In [68]:
np.ones(1)

array([1.])

In [70]:
arr=np.ones(5)

In [72]:
arr

array([1., 1., 1., 1., 1.])

In [73]:
arr+5

array([6., 6., 6., 6., 6.])

In [71]:
arr*3

array([3., 3., 3., 3., 3.])

In [ ]:
"""what is numpy
array
list vs Array
why array is faster then list
 Homogeneious :lestime
 memory alolocation:
    concept of referencing
    concept of resizing
    array -> sttically defined memory allocation not dynamic
              homogeneous
              1->vector
              2d->matrix
              3d->tensor

    vectorization :
    np does vectorization



In [75]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
arr=np.eye(5,dtype= int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [82]:
import pandas as pd
pd.DataFrame(arr)

0  1  2  3  4
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  0  0  0  0  1

In [85]:
import random
random.choice((1,2,3,4,5,6))

4

In [87]:
random.choice('Jyotirmoy')

'r'

In [88]:
random.randrange(1,10)

7

In [90]:
random.randrange(1,1000,10)


541

In [92]:
random.random()

0.6295518961177866

In [94]:
list = [1,2,3,4,5]
random.shuffle(list)

In [97]:
random.uniform(7,14) 

7.293660273153577

In [98]:
np.random.rand(2,3)

array([[0.22828261, 0.6989064 , 0.10297123],
       [0.16828055, 0.98016643, 0.96925968]])

In [100]:
np.random.rand(2,3,4)

array([[[0.9066921 , 0.21031076, 0.17452112, 0.89970016],
        [0.10442252, 0.444739  , 0.98064047, 0.60372469],
        [0.46165792, 0.60971755, 0.30813929, 0.80514509]],

       [[0.2021114 , 0.31428089, 0.93262869, 0.10704584],
        [0.79493272, 0.96476417, 0.70164907, 0.36803009],
        [0.46125018, 0.1445648 , 0.12651095, 0.0699395 ]]])

In [101]:
np.random.rand(1)

array([0.53058514])

In [102]:
np.random.randn(2,3)

array([[-0.39471733,  0.60579715, -1.2322895 ],
       [ 1.27112978,  0.24485026,  0.42980731]])

In [103]:
np.random.random_sample()

0.19417830331635078

In [105]:
arr=np.random.randint(1,5,size=(3,4))

In [106]:
arr.size


12

In [107]:
arr.reshape(2,6)

array([[3, 1, 3, 1, 3, 1],
       [3, 4, 2, 1, 4, 2]])

In [108]:
arr.reshape(2,1) # arrsize cannot change

ValueError: cannot reshape array of size 12 into shape (2,1)

In [109]:
arr.reshape(6,2)

array([[3, 1],
       [3, 1],
       [3, 1],
       [3, 4],
       [2, 1],
       [4, 2]])

In [110]:
arr.reshape(12,1)#twodimensional

array([[3],
       [1],
       [3],
       [1],
       [3],
       [1],
       [3],
       [4],
       [2],
       [1],
       [4],
       [2]])

In [111]:
arr.reshape(12,)

array([3, 1, 3, 1, 3, 1, 3, 4, 2, 1, 4, 2])

In [112]:
arr.reshape(12)

array([3, 1, 3, 1, 3, 1, 3, 4, 2, 1, 4, 2])

In [113]:
arr.reshape(3,4)

array([[3, 1, 3, 1],
       [3, 1, 3, 4],
       [2, 1, 4, 2]])

In [114]:
arr.reshape(4,3)

array([[3, 1, 3],
       [1, 3, 1],
       [3, 4, 2],
       [1, 4, 2]])

In [115]:
arr.reshape(4,-1)#when you don't know column number

array([[3, 1, 3],
       [1, 3, 1],
       [3, 4, 2],
       [1, 4, 2]])

In [118]:
arr.reshape(-1,6)#when you don't know row number

array([[3, 1, 3, 1, 3, 1],
       [3, 4, 2, 1, 4, 2]])

In [120]:
arr.reshape(12,1).base

array([[3, 1, 3, 1],
       [3, 1, 3, 4],
       [2, 1, 4, 2]])

In [121]:
arr

array([[3, 1, 3, 1],
       [3, 1, 3, 4],
       [2, 1, 4, 2]])

In [122]:
arr.reshape(2,2,3)

array([[[3, 1, 3],
        [1, 3, 1]],

       [[3, 4, 2],
        [1, 4, 2]]])

In [125]:
arr.reshape(1,2,2,3)

array([[[[3, 1, 3],
         [1, 3, 1]],

        [[3, 4, 2],
         [1, 4, 2]]]])

In [126]:
arr.reshape(4,3,1)

array([[[3],
        [1],
        [3]],

       [[1],
        [3],
        [1]],

       [[3],
        [4],
        [2]],

       [[1],
        [4],
        [2]]])

In [128]:
arr.ndim

2

In [130]:
arr2 = np.array([[2,3],[4,5]])
arr2

array([[2, 3],
       [4, 5]])

In [137]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
arr2 = np.zeros((1,3,4)) # 3 rows and 4 colsumns and 1 extra dimension
arr2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [139]:
arr2 = np.zeros((1,1,3,4)) # 3 rows and 4 colsumns and 1 extra dimension + 1 ed
arr2


array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [141]:
arr2.ndim

4

In [142]:
arr2.shape

(1, 1, 3, 4)

In [143]:
arr3 = np.zeros((2,3,4)) # 3 rows and 4 colsumns and 1 extra dimension
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [144]:
arr3.shape


(2, 3, 4)

In [147]:
arr1=np.random.randint(1,10,(5,6))
arr1

array([[7, 9, 7, 9, 8, 1],
       [3, 1, 5, 7, 8, 1],
       [4, 7, 3, 5, 4, 5],
       [4, 2, 3, 4, 2, 9],
       [9, 9, 2, 5, 2, 5]])

In [148]:
arr1>5

array([[ True,  True,  True,  True,  True, False],
       [False, False, False,  True,  True, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True,  True, False, False, False, False]])

In [ ]:
arr1

In [150]:
arr1[arr1>5] # all the elements where arr1 isd true

array([7, 9, 7, 9, 8, 7, 8, 7, 9, 9, 9])

In [151]:
arr1[arr1<5] # all the elements where arr1 isd true

array([1, 3, 1, 1, 4, 3, 4, 4, 2, 3, 4, 2, 2, 2])

In [152]:
arr1

array([[7, 9, 7, 9, 8, 1],
       [3, 1, 5, 7, 8, 1],
       [4, 7, 3, 5, 4, 5],
       [4, 2, 3, 4, 2, 9],
       [9, 9, 2, 5, 2, 5]])

In [158]:
arr1[0][1:3]

array([9, 7])

In [159]:
arr1[0,[1,3]]

array([9, 9])

In [161]:
arr1[2:4]

array([[4, 7, 3, 5, 4, 5],
       [4, 2, 3, 4, 2, 9]])

In [162]:
arr1[2:4,[0,2]]

array([[4, 3],
       [4, 3]])

In [166]:
arr1[2:5,0:2] # slicing of the array

array([[4, 7],
       [4, 2],
       [9, 9]])

In [5]:

arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [170]:
arr1

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [171]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [172]:
arr1+arr2

array([[4, 3, 3],
       [3, 4, 2],
       [3, 4, 3]])

In [173]:
arr1-arr2

array([[ 0, -1, -1],
       [-1,  0,  0],
       [ 1,  0, -1]])

In [174]:
arr1*arr2

array([[4, 2, 2],
       [2, 4, 1],
       [2, 4, 2]])

In [6]:
#matrix multiplication
arr1 @ arr2

array([[ 8, 12,  8],
       [ 6, 10,  7],
       [ 8, 12,  8]])

In [176]:
arr1 / arr2 #index wise devision

array([[1. , 0.5, 0.5],
       [0.5, 1. , 1. ],
       [2. , 1. , 0.5]])

In [177]:
arr1/0


C:\Users\jtrmb\AppData\Local\Temp\ipykernel_2932\1824492102.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [180]:
#BroadCasting
arr =np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [182]:
a = np.array([1,2,3,4])#columnwise addition
a

array([1, 2, 3, 4])

In [183]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [189]:
#column wise addition
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [190]:
a.T #treanspose

array([[1],
       [2],
       [3]])

In [191]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [192]:
a = np.array([1,2,3]) # no transpose will happen as it is 1 -d ,we need2-d
a.T

array([1, 2, 3])

In [193]:
arr1


array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [194]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [195]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [196]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [197]:
np.min(1)

1

In [198]:
arr1.flatten() #reduce higher dimesion to 1 dimensiuon

array([2, 1, 1, 1, 2, 1, 2, 2, 1])

In [201]:
#expand dimension >> expand the array by inserting new axis
arr = np.array([[1,2,3],[4,5,6]])


In [202]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
arr.sum

<function ndarray.sum>

In [205]:
np.sum(arr,axis=0)#row wiwise addition

array([5, 7, 9])

In [206]:
np.sum(arr,axis=1)#column wiwise addition

array([ 6, 15])

In [207]:
#expand_dims 
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [213]:
arr1=np.expand_dims(arr,axis=0) # increse dimension by 1
arr1

array([[[1, 2, 3],
        [4, 5, 6]]])

In [216]:
arr1.shape

(1, 2, 3)

In [217]:
arr2=np.expand_dims(arr1,axis=0) # increse dimension by 1
arr2


array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [218]:
arr2.shape

(1, 1, 2, 3)

In [234]:
arr1=np.ones(5)
arr1 = np.expand_dims(arr1,axis=1)
arr1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [233]:
arr1 = np.expand_dims(arr1,axis=0)
arr1

array([[1., 1., 1., 1., 1.]])

In [10]:
A = np.array([[1, 2, 3, 4]])


B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


C = A @ B
print(C)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [8]:
A.ndim

2

In [9]:
B.ndim

2